name: GitHub Trigger jenkins job
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://e281-222-252-16-153.ap.ngrok.io"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "vue-testing"